WifiCountryCode: "US"
VideoAntiFlickerRate: 60
VideoQualityDefault: "default"
NotifyOnMotionAlert: true
NotifyOnMotionTimeoutAlert: false
NotifyOnAudioAlert: false
NotifyOnButtonPressAlert: true
MotionRecordingWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/motionDetected"
AudioRecordingWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/"
UserRecordingWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/"
StatusUpdateWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/statusUpdated"
RegistrationWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/registered"
ButtonPressWebHookUrl: "http://192.168.178.2:11080/endpoint/@scrypted/arlo-local/public/buttonPressed"
